apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy-prom

spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  
  template:
    metadata:
      name: deploy-prom
      labels:
        app: prometheus
  
    spec:
      volumes:
      - name: storage-prom
        persistentVolumeClaim:
          claimName: pvc-prom
      containers:
      - name: prom
        image: anantj1/prometheus:v1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: "/data_prometheus"
            name: storage-prom
      