apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: pvc-prom
  labels:
    name: pvc-prom

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  
